// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqZWpVinNgWc8AQAs04I3MCgJlBCF0Eio',
    appId: '1:1039876358754:web:6644df45c0e799aadb873b',
    messagingSenderId: '1039876358754',
    projectId: 'worksphere-503b9',
    authDomain: 'worksphere-503b9.firebaseapp.com',
    storageBucket: 'worksphere-503b9.firebasestorage.app',
    measurementId: 'G-ZH145XFM0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDkZKeBmQdrL2k3VGHIvXU83LDLdVwwyo',
    appId: '1:1039876358754:android:c3df401c6d06b665db873b',
    messagingSenderId: '1039876358754',
    projectId: 'worksphere-503b9',
    storageBucket: 'worksphere-503b9.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDb59ye9a1IlRyZOWil9kONwp8-zWf7Uk',
    appId: '1:1039876358754:ios:fb8df4a6adf84649db873b',
    messagingSenderId: '1039876358754',
    projectId: 'worksphere-503b9',
    storageBucket: 'worksphere-503b9.firebasestorage.app',
    iosBundleId: 'com.worksphere.worksphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqZWpVinNgWc8AQAs04I3MCgJlBCF0Eio',
    appId: '1:1039876358754:web:86e8c1bb168024c4db873b',
    messagingSenderId: '1039876358754',
    projectId: 'worksphere-503b9',
    authDomain: 'worksphere-503b9.firebaseapp.com',
    storageBucket: 'worksphere-503b9.firebasestorage.app',
    measurementId: 'G-16JQS3CYMZ',
  );
}
